version: "3.6"
services:
  frontend:
    image: gcarvalho/frontend
    hostname: frontend
    ports:
      - "10000:8111"
    links:
      - backend
    environment:
      - BACKEND_HOST=backend:8110


  backend:
    image: gcarvalho/backend
    hostname: backend
    ports:
     - "10001:8110"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
